# Generated by Django 4.2.7 on 2023-11-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='contactNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='joinDate',
            field=models.DateField(null=True),
        ),
    ]
